nf-core/chipseq

docs/usage.md, nextflow.config
Copying the most updated version of check_max function from nf-core/rnaseq
=> Update check_max function

bin/post_peak_calling_processing.r
The post_peak_calling script was a big bottleneck in my runs.
One of the reasons was the loop was quite slow, I improved a little bit the code (summarized in this report http://rpubs.com/tiagochst/post_peak_calling_improvement).
=> Improving function speed

CHANGELOG.md, Singularity, environment.yml, nextflow.config
Self-explanatory? If it looks OK, Chuan requests us to wait to pull, to avoid merging issues...
=> Changed the pipeline version to 1.0

main.nf
=> Fix bug that countstat fails with skipDupRemoval on

bin/post_peak_calling_processing.r, bin/saturation_results_processing.r, conf/base.config, conf/test.config, docs/usage.md, main.nf, nextflow.config
Having a stab at refactoring the deepTools process in this pipeline. Instead of one huge process that takes ages, it should now be one per command executed. This means that several are able to go in parallel on larger systems and things should be easier to debug.
Bonus: The deepTools processes that can accept it should now be properly multithreaded, as they are given the number of cpus available.
Bonus: The number of windows used for the `plotFingerprint` step is now configurable (and smaller for test config)
Bonus: Hopefully more output from nextflow could mean that the travis tests now pass. However, I have a nasty feeling that `computeMatrix` will still be too slow and bugger this up. We'll see how far we get...
There's a little easter egg hidden in here too. Let's see if you notice...
=> Refactor deeptools

.travis.yml, conf/base.config, environment.yml, nextflow.config
Update conda packages. Fixes #70
Update style to match latest linting and template changes.
Tests will fail until new nf-core tools package is release on PyPI.
=> Update conda packages, process.container style

.travis.yml, Dockerfile, environment.yml
Initial PR to rebuild `Docker` container for https://github.com/nf-core/chipseq/pull/76
=> Rebuild Docker container for PR #76

nextflow.config
Forgot to update these in `nextflow.config` when I changed them in `main.nf`
=> Change parameter names in nextflow.config

environment.yml
Add `preseq` to `environment.yml`. Initial PR to build `docker` container.
=> Add preseq to environment

.travis.yml, CHANGELOG.md, Dockerfile, assets/multiqc/multiqc_config.yaml, conf/base.config, environment.yml, main.nf, nextflow.config
=> Bump version to 1.0.0

CHANGELOG.md, README.md
This PR will need to be merged into `dev` just before https://github.com/nf-core/chipseq/pull/90 is merged into `master`. Just ensures that the correct release date is set in `CHANGELOG.md`
=> Update date in CHANGELOG

CHANGELOG.md, README.md
=> Dev > Master fix typo

.travis.yml, CHANGELOG.md, Dockerfile, README.md, environment.yml, nextflow.config
=> Bump version to 1.0.1dev

main.nf
=> Fix gene.bed parameter name bug

.github/CONTRIBUTING.md, .github/markdownlint.yml, README.md, docs/output.md, docs/usage.md
=> Update markdownlint checks

.travis.yml, CHANGELOG.md, Dockerfile, environment.yml, main.nf, nextflow.config
=> Bump version to 1.1.0

.travis.yml, CHANGELOG.md, Dockerfile, README.md, conf/base.config, main.nf, nextflow.config
=> Address comments for PR #114 (Dev > Master)

.travis.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Bump version to 1.1.1dev

CHANGELOG.md, main.nf
=> Fix skip_trimming bug

CHANGELOG.md, environment.yml, main.nf
=> Added multicore support for Trim Galore!

CHANGELOG.md, environment.yml, main.nf
* See https://github.com/nf-core/atacseq/pull/65#issuecomment-557839116
* Update `MultiQC`
=> Fix TrimGalore core logic and update MultiQC

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/branch.yml, .github/workflows/ci.yml, .github/workflows/linting.yml, .gitignore, .travis.yml, CHANGELOG.md, CODE_OF_CONDUCT.md, Dockerfile, README.md, docs/usage.md, main.nf, nextflow.config
* Replace `--skip_diff_analysis` with `--skip_consensus_peaks` to more elegantly skip the consensus peak generation and differential analysis if required.
=> Add GitHub Actions and some template updates

.github/workflows/branch.yml, .github/workflows/ci.yml, CHANGELOG.md, main.nf
Fixes https://github.com/nf-core/chipseq/issues/132
=> Specify temp dir for sort commands

CHANGELOG.md, bin/plot_homer_annotatepeaks.r
Fixes https://github.com/nf-core/atacseq/issues/73
=> Change the way NA values are evaluated in annotatePeaks file

.github/workflows/ci.yml, CHANGELOG.md, environment.yml, main.nf
=> Update packages in environment

CHANGELOG.md, environment.yml
=> Downgrade markdown

CHANGELOG.md, Dockerfile, README.md, bin/featurecounts_deseq2.r, bin/plot_homer_annotatepeaks.r, docs/output.md, docs/usage.md, main.nf, nextflow.config
* Add `.Rprofile` and `.Renviron` empty files to container and refer to them in `nextflow.config` to avoid local clashes
* `--deseq2_vst` allows users to pick the much faster `vsn` transform over `rlog` for differential analysis
=> Add deseq2_vsn parameter

nextflow.config
=> fix path of `.Rprofile` and `.Renviron`

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Bump versions to 1.2.0

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
Many thanks for contributing to nf-core/chipseq!
Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).
**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/chipseq/tree/master/.github/CONTRIBUTING.md)
=> Bump version to 1.3.0dev

environment.yml
Many thanks for contributing to nf-core/chipseq!
Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).
**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/chipseq/tree/master/.github/CONTRIBUTING.md)
=> Update env to get release tests passing

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
Many thanks for contributing to nf-core/chipseq!
Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).
**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/chipseq/tree/master/.github/CONTRIBUTING.md)
=> Fix Conda environment for patch release

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
Many thanks for contributing to nf-core/chipseq!
Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).
**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/chipseq/tree/master/.github/CONTRIBUTING.md)
=> 1.2.2 patch release to fix Conda environment

CHANGELOG.md, conf/modules.config
Set `mode` of `publishDir` in the modules config file using the `publish_dir_mode` parameter.
=> Bring back publish_dir_mode

modules/local/multiqc_custom_peaks.nf
Should fix https://github.com/nf-core/chipseq/issues/274
=> Replace last remaining vanilla Linux Biocontainer

.github/workflows/awsfulltest.yml, .github/workflows/awstest.yml, .github/workflows/branch.yml, .github/workflows/ci.yml, .github/workflows/fix-linting.yml, .github/workflows/linting.yml, .prettierignore, CHANGELOG.md, README.md, assets/email_template.html, nextflow.config
Merging template after the release of tools version 2.4.0
=> Merging template 2.4.0

CHANGELOG.md, modules/local/multiqc.nf, nextflow.config
* Bump pipeline version to 2.0.0
* Update `multiqc` version to match the one in `CUSTOM_DUMPSOFTWAREVERSIONS`
=> Bump pipeline version to 2.0

CHANGELOG.md, conf/modules.config
* Move `ANNOTATE_BOOLEAN_PEAKS` under `skip_peak_annotation` in modules.config
* Update parameters table in changelog
=> Fix modules.config 

.gitignore, CITATIONS.md, assets/samplesheet.csv, conf/modules.config, modules/local/multiqc.nf, nextflow_schema.json, workflows/chipseq.nf
* Fix nf-core lint after `.gitignore` change.
* Update citations 
* Remove differential analysis from nextflow_schema.json
* Fix multiqc report, deseq and homer annotate were not loaded
* Fix labels for deeptools plotfingerprint
=> Address review comments

.github/workflows/awsfulltest.yml, .github/workflows/awstest.yml, .prettierignore, CITATION.cff, assets/adaptivecard.json, assets/methods_description_template.yml, assets/multiqc_config.yml, docs/usage.md, lib/NfcoreTemplate.groovy, lib/Utils.groovy, lib/WorkflowChipseq.groovy, modules/local/multiqc.nf, modules/nf-core/multiqc/main.nf, nextflow.config, nextflow_schema.json, workflows/chipseq.nf
=> Merging template 2.6

nextflow_schema.json
=> Correct link to blacklist directory

.editorconfig, .github/ISSUE_TEMPLATE/bug_report.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/awsfulltest.yml, .github/workflows/awstest.yml, .github/workflows/branch.yml, .github/workflows/clean-up.yml, .github/workflows/linting.yml, .pre-commit-config.yaml, README.md, bin/check_samplesheet.py, conf/base.config, conf/igenomes.config, conf/test_full.config, docs/usage.md, lib/NfcoreSchema.groovy, lib/WorkflowChipseq.groovy, lib/WorkflowMain.groovy, modules/local/annotate_boolean_peaks.nf, modules/local/multiqc_custom_peaks.nf, modules/local/samplesheet_check.nf, nextflow.config, tower.yml
Template update nf-core tools v2.8
=> Template update nf-core tools v2.8

CHANGELOG.md, nextflow.config
See https://github.com/nf-core/tools/pull/2286
=> Set a default registry outside of profile scope

CHANGELOG.md, bin/check_samplesheet.py
=> Check for sample IDs characters in samplesheet

conf/modules.config, subworkflows/local/bam_peaks_call_qc_annotate_macs2_homer.nf, workflows/chipseq.nf
Second item of https://github.com/nf-core/chipseq/issues/398
=> use subworkflows/local/bam_peaks_call_qc_annotate_macs2_homer from nf-core/atacseq

README.md, conf/modules.config, subworkflows/local/bed_consensus_quantify_qc_bedtools_featurecounts_deseq2.nf, workflows/chipseq.nf
=> Clean up and removal of double slashes

CHANGELOG.md, subworkflows/local/bed_consensus_quantify_qc_bedtools_featurecounts_deseq2.nf
=> Fix how replicates are set for downstream analysis
